name: Parium
favicon: null
layout_spectrum: 0.7637
typography_spectrum: 0.42781
title: Parium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4271b9'
    - '#221e1f'
    - '#cad4e8'
    - '#a6a3a4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
